FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime

ENV APP_DIR /workspace
WORKDIR ${APP_DIR}

COPY requirements.txt ${APP_DIR}

RUN apt-get update && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# COPY ./src/ ${APP_DIR}/src/

# 環境変数設定
ENV PYTHONPATH="/workspace/src"

